### ISSUE TITLE
Definition of an REST API

### ISSUE THREAD

**Issue by Simon-Deuring** [Simon-Deuring/labgrid-frontend-mle#6]
**Description:**

The data about places and resources that is requested in the backend and provided by the coordinator needs to be displayed in the frontend. A REST API can be used to transfer data between backend and frontend.

**Acceptance criteria:**
- [x] REST method for retrieval of places
- [x] REST method for retrieval of hardware resources
- [x] Methods can be called via REST calls

**Additional information:**
[Postman](https://www.postman.com/) can be used to test the REST API of the backend.

**Comment by deathcat0011** [comment]
Needs additional requirements of reading resources and places from labgrid config/backend
