### ISSUE TITLE
Inconsistent table columns

### ISSUE THREAD

**Issue by Simon-Deuring** [Simon-Deuring/labgrid-frontend-mle#82]
**Description:**
The place page shows a table with interesting bits of information. However, for some places the columns are not equally wide. When changing between different places this is visible as the content within the table moves.

![table1](https://user-images.githubusercontent.com/33379546/144746999-212bf883-c2b6-49fd-9358-9dced1852a2f.PNG)
![table2](https://user-images.githubusercontent.com/33379546/144747002-55cd04a2-0fcd-4539-bafe-156b88eb31a5.PNG)

**Reproduction:**
Run the frontend locally, then open [localhost:4200/ ](http://localhost:4200/). Open the sidebar and click at different places from the list. Look at the displayed table while doing so.

**Acceptance Criteria:**
- [ ] Set the width of the columns to a fixed size or 50%
- [ ] Find out why the layout changes

**Comment by NeptunFlosse** [comment]
This was already fixed with your suggestion to issue #23
