### ISSUE TITLE
Read Hardware Resources from Server

### ISSUE THREAD

**Issue by NeptunFlosse** [Simon-Deuring/labgrid-frontend-mle#9]
**Description:**

Before the hardware resources can be displayed they need to be retrieved from the backend/server. Therefore, in the frontend the server's remote procedures have to be called.

**Acceptance criteria:**
- [x] Call remote procedures of server
- [x] Save response in a suitable data structure

**Comment by deathcat0011** [comment]
This issue can probably be closed as soon as #77 is merged.
